filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/jindo/production.log"
    multiline.pattern: '^I,'
    multiline.negate: true
    multiline.match: after
    include_lines: ['^I,']
    fields:
      server: jindo

  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/husky/.log"
    fields:
      server: husky

  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/samoyed/.log"
    fields:
      server: samoyed

  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/schnauzer/http.log"
    fields:
      server: schnauzer
      classification: http
  
  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/schnauzer/socket.log"
    fields:
      server: schnauzer
      classification: socket
  
  - type: log
    enabled: true
    paths:
      - "/usr/share/filebeat/logs/print_admission_ticket/.log"
    fields:
      server: print_admission_ticket

output.logstash:
  hosts: ['logstash:5001']